---
asnos:

   sp-266-1:
       loopback: 172.26.90.51
       asn: 65100

   sp-266-2:
       loopback: 172.26.90.52
       asn: 65100

   le-266-1-1:
       asn: 65001
       loopback: 172.26.90.21
       clag_sys_mac: 44:39:39:FF:00:D3
       clag_anycast_ip: 192.168.200.1
       server_id: 1

   le-266-1-2:
       asn: 65002
       loopback: 172.26.90.22
       clag_sys_mac: 44:39:39:FF:00:D3
       clag_anycast_ip: 192.168.200.1
       server_id: 1

   le-266-2-1:
       asn: 65003
       loopback: 172.26.90.23
       clag_sys_mac: 44:39:39:FF:00:D4
       clag_anycast_ip: 192.168.200.2
       server_id: 2

   le-266-2-2:
       asn: 65004
       loopback: 172.26.90.24
       clag_sys_mac: 44:39:39:FF:00:D4
       clag_anycast_ip: 192.168.200.2
       server_id: 2

   le-266-3-1:
       asn: 65005
       loopback: 172.26.90.25
       clag_sys_mac: 44:39:39:FF:00:D5
       clag_anycast_ip: 192.168.200.3
       server_id: 3

   le-266-3-2:
       asn: 65006
       loopback: 172.26.90.26
       clag_sys_mac: 44:39:39:FF:00:D5
       clag_anycast_ip: 192.168.200.3
       server_id: 3

vxlan:
   vni:
      - 417
      - 419
