---

  - hosts: leaf-vxlan
    roles:
       - hostnames
       - bridges
       - interfaces
       - bgp
       - vxlan

  - hosts: spines
    roles:
       - hostnames
       - interfaces
       - bgp
