---
  - name: Capture if Spine or Leaf
    set_fact:
      type: "{{ inventory_hostname | regex_replace('-(.*)$') | string }}"


  - name: Configure BGP Unnumbered
    nclu:
      atomic: true
      template: |

             add routing route-map LOOPBACK permit 10 match interface lo
             add bgp autonomous-system {{ asnos[inventory_hostname].asn }}
             add bgp router-id {{ asnos[inventory_hostname].loopback }}
             add bgp bestpath as-path multipath-relax
             add bgp neighbor fabric peer-group
             add bgp neighbor fabric remote-as external
             add bgp neighbor fabric description Internal_Fabric_Network
             add bgp neighbor fabric capability extended-nexthop

             {% if type == "le" %}
             {% for bgpiface in range(4,6) %}
             add bgp neighbor swp{{bgpiface}} peer-group fabric
             {% endfor %}
             {% endif %}

             {% if type == "sp" %}
             {% for bgpiface in range(1,7) %}
             add bgp neighbor swp{{bgpiface}} peer-group fabric
             {% endfor %}
             add bgp ipv4 unicast maximum-paths 64
             {% endif %}


             add bgp evpn neighbor fabric activate
             add bgp evpn advertise-all-vni

             add bgp ipv4 unicast redistribute connected route-map LOOPBACK
             add bgp ipv6 unicast neighbor fabric activate
